In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
my_array = np.array(my_list)
my_array

array([1, 2, 3])

In [6]:
np.array([4,5,6])

array([4, 5, 6])

In [7]:
np.array([7,8,9,])

array([7, 8, 9])

In [8]:
my_list = [[1,2,3],[4,5,6],[7,8,9]]
my_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,100,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [11]:
np.arange(1,56,8)

array([ 1,  9, 17, 25, 33, 41, 49])

In [12]:
np.linspace(1,20,40)

array([ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
        3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
        5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
        8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026,
       10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
       13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
       15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
       18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ])

In [14]:
np.linspace(-25,-1,40)

array([-25.        , -24.38461538, -23.76923077, -23.15384615,
       -22.53846154, -21.92307692, -21.30769231, -20.69230769,
       -20.07692308, -19.46153846, -18.84615385, -18.23076923,
       -17.61538462, -17.        , -16.38461538, -15.76923077,
       -15.15384615, -14.53846154, -13.92307692, -13.30769231,
       -12.69230769, -12.07692308, -11.46153846, -10.84615385,
       -10.23076923,  -9.61538462,  -9.        ,  -8.38461538,
        -7.76923077,  -7.15384615,  -6.53846154,  -5.92307692,
        -5.30769231,  -4.69230769,  -4.07692308,  -3.46153846,
        -2.84615385,  -2.23076923,  -1.61538462,  -1.        ])

In [15]:
np.linspace(0.3, 2.47, 10)

array([0.3       , 0.54111111, 0.78222222, 1.02333333, 1.26444444,
       1.50555556, 1.74666667, 1.98777778, 2.22888889, 2.47      ])

In [16]:
np.linspace(1,25)

array([ 1.        ,  1.48979592,  1.97959184,  2.46938776,  2.95918367,
        3.44897959,  3.93877551,  4.42857143,  4.91836735,  5.40816327,
        5.89795918,  6.3877551 ,  6.87755102,  7.36734694,  7.85714286,
        8.34693878,  8.83673469,  9.32653061,  9.81632653, 10.30612245,
       10.79591837, 11.28571429, 11.7755102 , 12.26530612, 12.75510204,
       13.24489796, 13.73469388, 14.2244898 , 14.71428571, 15.20408163,
       15.69387755, 16.18367347, 16.67346939, 17.16326531, 17.65306122,
       18.14285714, 18.63265306, 19.12244898, 19.6122449 , 20.10204082,
       20.59183673, 21.08163265, 21.57142857, 22.06122449, 22.55102041,
       23.04081633, 23.53061224, 24.02040816, 24.51020408, 25.        ])

In [17]:
np.linspace(1,25,50)

array([ 1.        ,  1.48979592,  1.97959184,  2.46938776,  2.95918367,
        3.44897959,  3.93877551,  4.42857143,  4.91836735,  5.40816327,
        5.89795918,  6.3877551 ,  6.87755102,  7.36734694,  7.85714286,
        8.34693878,  8.83673469,  9.32653061,  9.81632653, 10.30612245,
       10.79591837, 11.28571429, 11.7755102 , 12.26530612, 12.75510204,
       13.24489796, 13.73469388, 14.2244898 , 14.71428571, 15.20408163,
       15.69387755, 16.18367347, 16.67346939, 17.16326531, 17.65306122,
       18.14285714, 18.63265306, 19.12244898, 19.6122449 , 20.10204082,
       20.59183673, 21.08163265, 21.57142857, 22.06122449, 22.55102041,
       23.04081633, 23.53061224, 24.02040816, 24.51020408, 25.        ])

In [19]:
np.linspace(1,36,30)

array([ 1.        ,  2.20689655,  3.4137931 ,  4.62068966,  5.82758621,
        7.03448276,  8.24137931,  9.44827586, 10.65517241, 11.86206897,
       13.06896552, 14.27586207, 15.48275862, 16.68965517, 17.89655172,
       19.10344828, 20.31034483, 21.51724138, 22.72413793, 23.93103448,
       25.13793103, 26.34482759, 27.55172414, 28.75862069, 29.96551724,
       31.17241379, 32.37931034, 33.5862069 , 34.79310345, 36.        ])

In [20]:
np.zeros(4)

array([0., 0., 0., 0.])

In [21]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.zeros((3,4), dtype=str)

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [26]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
np.ones(4,dtype=bool)

array([ True,  True,  True,  True])

In [30]:
np.zeros((2,5), dtype=bool)

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [31]:
np.full((3,4),4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [32]:
np.full((6,7),"steve")

array([['steve', 'steve', 'steve', 'steve', 'steve', 'steve', 'steve'],
       ['steve', 'steve', 'steve', 'steve', 'steve', 'steve', 'steve'],
       ['steve', 'steve', 'steve', 'steve', 'steve', 'steve', 'steve'],
       ['steve', 'steve', 'steve', 'steve', 'steve', 'steve', 'steve'],
       ['steve', 'steve', 'steve', 'steve', 'steve', 'steve', 'steve'],
       ['steve', 'steve', 'steve', 'steve', 'steve', 'steve', 'steve']],
      dtype='<U5')

In [35]:
type(np.full(5,6))

numpy.ndarray

In [39]:
np.eye(5,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

In [40]:
np.eye(2,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [41]:
np.random.rand(4,4)

array([[0.08268574, 0.50111809, 0.63776698, 0.65878946],
       [0.65705582, 0.74048836, 0.00175082, 0.6278335 ],
       [0.69122229, 0.7461113 , 0.45561232, 0.83088108],
       [0.32107704, 0.52262694, 0.39230993, 0.59221596]])

In [42]:
np.random.rand(5)

array([0.6905497 , 0.87335353, 0.12712199, 0.07649615, 0.22436896])

In [43]:
np.random.randn(4)

array([-0.61106037, -0.15921373, -0.15736075, -1.76536105])

In [44]:
np.random.randn(4,4)

array([[ 0.18408783, -0.70063737,  1.13764106,  0.04525498],
       [-0.16979991,  1.74194593, -1.04704468, -0.89305761],
       [ 1.84047206,  1.26153113,  0.23846304, -0.98183811],
       [-1.68407216, -0.86670865, -0.18951776, -1.43107658]])

In [47]:
np.random.randint(3,26,10)

array([ 7,  3, 18, 24, 20, 11, 14, 10, 18,  7])

In [48]:
np.random.randint(-27,-1,10)

array([-24,  -6, -21, -12, -10,  -8, -18, -23, -14, -19])

In [50]:
np.random.randint(20, size=10 )


array([18, 18,  6,  6, 17, 14,  0, 19,  3, 11])

In [51]:
np.random.randint(4, size=10)

array([1, 3, 1, 2, 3, 3, 2, 2, 0, 3])

In [52]:
np.random.randint(1,34,5)

array([14, 26,  4,  1, 12])

In [59]:
np.random.randint(-23,35, size=(5,5))

array([[  2,   9,  30,  -1,  -8],
       [  5,  34, -19,   7,   9],
       [ 24,   1,  32, -23,  28],
       [-17,  16,  -2,  15,  24],
       [ 17,  -7, -17,  -4,  24]])

In [62]:
np.random.randint(1,[2,4,8],size=(4,3))

array([[1, 2, 2],
       [1, 1, 4],
       [1, 2, 5],
       [1, 3, 6]])

In [71]:
np.random.randint([2,5,9],[4,8,13])

array([ 2,  5, 10])

In [73]:
arr = np.arange(36)
rand_arr = np.random.randint(0,50,10)

In [76]:
arr.shape

(36,)

In [77]:
rand_arr.shape

(10,)

In [78]:
arr.reshape(1,36)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35]])

In [79]:
arr.reshape(2,18)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35]])

In [82]:
arr.reshape(12,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35]])

In [85]:
arr.reshape(-1,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [90]:
arr.reshape(2,2,9)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23, 24, 25, 26],
        [27, 28, 29, 30, 31, 32, 33, 34, 35]]])

In [101]:
a = arr.reshape(3,4,3)

In [93]:
arr.max()

35

In [94]:
arr.min()

0

In [95]:
arr.argmax()

35

In [98]:
arr.size

36

In [99]:
arr.dtype

dtype('int64')

In [100]:
type(arr)

numpy.ndarray

In [103]:
a.ndim

3